Add animated svg to DarkModeToggle
backmeupplz/fondu pull request #40
Opened 2021-07-30 12:57 UTC by RobuASD

2021-07-30 19:13 UTC, backmeupplz requested changes

2021-07-30 19:13 UTC, backmeupplz commented on src/components/DarkModeToggle.tsx
> +  const [isDarkMode, setDarkMode] = React.useState(false)
Давай-ка вот этот стейт брать из `appStore`

2021-07-31 00:50 UTC, backmeupplz requested changes

2021-07-31 00:50 UTC, backmeupplz commented on src/components/DarkModeToggle.tsx
> +//appStore.theme
Этот комментарий не нужен

2021-07-31 00:50 UTC, backmeupplz commented on src/components/DarkModeToggle.tsx
> +    isDarkMode === 'dark' ? 'dark' : 'light'
Хм, можно же просто сюда скормить `appStore.theme`, нет?

2021-07-31 00:55 UTC, RobuASD commented on src/components/DarkModeToggle.tsx
> +    isDarkMode === 'dark' ? 'dark' : 'light'
Согласен, что-то не подумал)

2021-08-03 21:59 UTC, merged