Add, Replacing language buttons with dropdown list
backmeupplz/fondu pull request #42
Opened 2021-08-06 12:23 UTC by RobuASD

2021-08-07 22:35 UTC, backmeupplz requested changes

2021-08-07 22:35 UTC, backmeupplz commented on src/components/LanguageButtons.tsx
> +                      {flagForLanguage(k)}
Давай уберем флаги

2021-08-07 22:35 UTC, backmeupplz commented on src/i18n/locales/en.json
> +  "language":"GB"
У кого-то prettier отключен? 😅

2021-08-08 04:58 UTC, RobuASD commented on src/components/LanguageButtons.tsx
> +                      {flagForLanguage(k)}
Тогда будет en и ru
![image](https://user-images.githubusercontent.com/84847053/128621310-cbb0a433-30cd-49d5-a019-ee81bc332f56.png)

2021-08-08 04:59 UTC, RobuASD commented on src/i18n/locales/en.json
> +  "language":"GB"
Странно что но не сработал..

2021-08-17 16:08 UTC, merged