Create new slider and fix mobile version
backmeupplz/fondu pull request #44
Opened 2021-08-24 06:10 UTC by mormo669

2021-08-25 01:16 UTC, backmeupplz requested changes

2021-08-25 01:16 UTC, backmeupplz commented on src/components/Button.tsx
> +  // 'min-w-max',
Не оставляй закомментированный код в пулл реквестах

2021-08-25 01:16 UTC, backmeupplz commented on src/components/Header.tsx
> +// import Navigation from 'components/Navigation'
Удали закомментированный код

2021-08-25 01:16 UTC, backmeupplz commented on src/components/Header.tsx
> +  // 'flex-row',
Удали закомментированный код

2021-08-25 01:16 UTC, backmeupplz commented on src/components/Header.tsx
> +      {/* <Navigation /> */}
Удали закомментированный код

2021-08-25 01:16 UTC, backmeupplz commented on src/views/ERC721TokenSettings.tsx
> +            <div className="min-w-max">
Классы — только через `classnames`

2021-08-25 01:16 UTC, backmeupplz commented on src/components/Slider.tsx
> +        onClick={() => (appStore.network = 'test')}
Здесь не `()` нужны, а `{}`

2021-08-25 01:16 UTC, backmeupplz commented on src/components/Slider.tsx
> +        intlKey={'buttonTestNetwork'}
Здесь не нужны `{}`

2021-08-25 01:16 UTC, backmeupplz commented on src/views/ERC20TokenSettings.tsx
> +            <div className="min-w-max">
Классы только через classnames

2021-08-25 01:16 UTC, backmeupplz commented on src/components/Wallet/index.tsx
> +          <div className="min-w-max">
Классы только через classnames

2021-08-25 01:16 UTC, backmeupplz commented on src/components/Slider.tsx
> +      ></SliderButton>
Если внутри ничего нет, сделай самозакрывающийся тег типа `<tag />`

2021-08-25 01:16 UTC, backmeupplz commented on src/components/Slider.tsx
> +        onClick={() => (appStore.network = 'real')}
Тут нужны `{}`

2021-08-25 01:16 UTC, backmeupplz commented on src/components/Slider.tsx
> +      ></SliderButton>
Тут нужен самозакрывающийся тег

2021-08-25 01:16 UTC, backmeupplz commented on src/components/Slider.tsx
> +        intlKey={'buttonRealNetwork'}
Здесь не нужны `{}`

2021-08-28 05:27 UTC, mormo669 commented on src/components/Wallet/index.tsx
> +          <div className="min-w-max">
при classnames выдаёт ошибку и предлагает замену на className

2021-08-29 21:43 UTC, backmeupplz requested changes

2021-08-29 21:43 UTC, backmeupplz commented on src/views/TokenType.tsx
> +    <div className="flex flex-row  space-x-3 justify-evenly text-2xl py-4 items-center">
Классы только через `classnames`

2021-08-29 21:43 UTC, backmeupplz commented on src/components/Button.tsx
> +export { Button, buttonSize }
Тебе не нужно экспортить `buttonSize`. Если ты везде оборачиваешь кнопку в контейнер с `buttonSize`, так просто оберни его в этом компоненте. Если нужно где-то оборачивать, а где-то нет — добавь `props` в `Button` компонент и настраивай стили соответственно.

2021-09-05 23:37 UTC, backmeupplz requested changes

2021-09-05 23:37 UTC, backmeupplz commented on src/views/ERC721TokenSettings.tsx
> +              size={true}
Непонятно, что такое `size`.

2021-09-05 23:37 UTC, backmeupplz commented on src/components/Wallet/index.tsx
> +          {/* <div className={buttonSize}> */}
Не пушь в PR закомментированный код

2021-09-05 23:37 UTC, backmeupplz commented on src/components/Slider.tsx
> +}
Добавляй между компонентами пустую строку

2021-09-05 23:37 UTC, backmeupplz commented on src/components/Slider.tsx
> +const Slider: FC = () => {
Если у этого компонента не надо указывать props, то не надо лишний раз указывать тип `FC`

2021-09-05 23:37 UTC, backmeupplz commented on src/components/Button.tsx
> +        ' ' +
Какой-то непонятный хак, его быть не должно. Если хочешь — делай тут массив, а не соединяй строки

2021-09-05 23:37 UTC, backmeupplz commented on src/components/Button.tsx
> +const buttonSize = classnames('min-w-max')
Что такое `buttonSize`? Непонятно. Назови переменную понятнее.

2021-09-08 23:11 UTC, backmeupplz requested changes

2021-09-08 23:11 UTC, backmeupplz commented on src/components/Wallet/index.tsx
> +            maxSize={true}
Можно просто сделать `maxsize` — будет автоматом true, не нужно писать прямо `maxSize={true}`

2021-09-11 07:41 UTC, mormo669 commented on src/components/Slider.tsx
> +        onClick={() => (appStore.network = 'test')}
Done

2021-09-11 19:10 UTC, backmeupplz requested changes

2021-09-11 19:10 UTC, backmeupplz commented on src/components/Slider.tsx
> +        onClick={() => {appStore.network = 'test'}}
Включи у себя prettier и format on save

2021-09-16 22:53 UTC, merged